CASE WHEN SUBSTRING(NEO_REF_INST_NBR_ALIAS,1,1) = 'E'
THEN CONCAT(
SUBSTRING(REPLACE(NEO_REF_INST_NBR_ALIAS,'E',''),1,4),
REGEXP_REPLACE(SUBSTRING(REPLACE(NEO_REF_INST_NBR_ALIAS,'E',''),5),'^0*','')
)
ELSE